### PR TITLE
CI First draft

### LINKED ISSUE #3: Continuous integration
We should cover continuous integration for testing of software and packaging.

We currently use
- [travis-ci](https://travis-ci.com/) for `linux` and `osx`
- [appveyor](https://www.appveyor.com/) for `win`

We also use https://nightli.es/ for triggering nightly builds to make sure code doesn't go stale due to changes in upstream dependencies.

We try to make this easier by using a `devtools/` boilerplate:
https://github.com/omnia-md/devtools

### PR DESCRIPTION
**Pull request by Lnaden**
Page ready for review.

@pgrinaway or @bas-rustenburg could you look at this one?

Fixes #3

### CODE REVIEW

**Comment by jchodera** [comment]
This is great! All that's missing is some pointers to existing travis configurations, for example MDTraj, yank, or even the devtools boilerplate repo in the omnia-md org.

**Comment by jchodera** [comment]
One of the major goals here is to make it simple for someone to get started by copying something that works and tweaking it to their needs (but hopefully not needing to tweak it too much that it looks unfamiliar to other developers).

**Comment by Lnaden** [comment]
Okay, I'll add some pointers to examples.

**Comment by Lnaden** [comment]
Examples ready for review

**Pull request merged**
