### PR TITLE
Update README with index of documents

### PR DESCRIPTION
**Pull request by jchodera**
First draft at front page

### CODE REVIEW

**Comment by jchodera** [comment]
README preview [here](https://github.com/choderalab/software-development/blob/18a3a801f5ff92270f7d8f48077ae0706c66b2d4/README.md).

@andrrizzi @Lnaden @bas-rustenburg @pgrinaway @gregoryross : Can you take a look at the preview and see if this looks decent?

**Comment by andrrizzi** [comment]
Looks great to me!

**Comment by gregoryross** [comment]
Looks excellent. Great job everyone!

**Comment by jchodera** [comment]
[Updated README](https://github.com/choderalab/software-development/blob/9dacc52ac3386496d547e36c8647735950d2271e/README.md) with draft of [Philosophy](https://github.com/choderalab/software-development/blob/9dacc52ac3386496d547e36c8647735950d2271e/PHILOSOPHY_AND_SCOPE.md) and [Documentation](https://github.com/choderalab/software-development/blob/9dacc52ac3386496d547e36c8647735950d2271e/DOCUMENTATION.md) sections.

**Comment by jchodera** [comment]
There are so many changes here that I'll merge this and we can start with small separate PRs for fixes tomorrow.

**Pull request merged**
