### PR TITLE
Draft of licensing notes

### PR DESCRIPTION
**Pull request by pgrinaway**
Draft that addresses #5. Ready to review.

### CODE REVIEW

**Comment by jchodera** [comment]
We should definitely include a link to the [Open Source Initiative](https://opensource.org/), since this is the widely-recognized definitive body that designates "open source" licenses.

**Comment by pgrinaway** [comment]
>We should definitely include a link to the Open Source Initiative, since this is the widely-recognized definitive body that designates "open source" licenses.

Ok!

**Comment by jchodera** [comment]
[This article](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002598) ("A Quick Guide to Software Licensing for the Scientist-Programmer") may also be useful to link to

**Comment by jchodera** [comment]
This looks great!

Can we also make a recommendation? I'd suggest the most permissive license (MIT) might be a good default recommendation since it allows for your software to have the "fullest life", by being useful for both academic and commercial purposes with minimal risk.

I might also add a paragraph about [software relicensing](https://en.wikipedia.org/wiki/Software_relicensing): What happens if you need to change licenses, or also distribute the software under a second (different) license? This can cause headaches since all authors have to agree, and is a strong argument for why starting with a permissive license is often optimal.

**Comment by pgrinaway** [comment]
>Can we also make a recommendation? 

I'm concerned about doing this since there is no one "right" answer, and there have been uncountable flame wars over the issue. I don't want to stir up too many feelings, just provide some helpful guide to selecting a license. 

>I might also add a paragraph about software relicensing:

I did have some of that but I think it could be split off to be on its own. Will do now.

**Comment by pgrinaway** [comment]
Ok, I've added both. I noted that the legal issues involved in maintaining a copyleft license while simultaneously facilitating commercial collaboration can become burdensome, so we recommend a permissive license such as MIT.

**Comment by jchodera** [comment]
Awesome! Thanks so much! 

Hopefully the license issues are places where molssi.org can provide clarity.

**Pull request merged**
