### PR TITLE
Create VERSION_CONTROL.md

### PR DESCRIPTION
**Pull request by bas-rustenburg**

### CODE REVIEW

**Comment by bas-rustenburg** [comment]
Working on this now.

**Comment by bas-rustenburg** [comment]
By feature branches, do you mean Github flow? https://guides.github.com/introduction/flow/index.html

I assume we don't want to recommend the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/)  model, which is overkill for small projects.

**Comment by jchodera** [comment]
Thanks! The hope is to get people in the lab and other labs to do the same thing, not different things, to make it easier to collaborate. The overview of different systems is great, but we should open or close with a specific recommendation to use GitHub and either the fork merge model or the feature branch model. I think most of us have found the feature branch model works better, so maybe we should recommend that for core developers but link the fork merge model docs as a way external devs can contribute?

**Comment by bas-rustenburg** [comment]
Added recommendation to use github, and the branching model. Mentioned the fork model as an alternative for people that want to allow outside collaborators, or experimental development on a codebase.

Also mentioned the more professional git-flow model, while mentioning that it may be overkill for small projects.

**Comment by jchodera** [comment]
Looks great, thanks! Merge when ready!

**Pull request merged**
